font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

  size: 14

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true
