# Mouse
mouse:
  # Time interval to wait for clicks to register (in ms)
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # Show/hide mouse cursor when typing
  hide_when_typing: true

  # Modifier key to use for clicking on URLs
  modifiers: Command

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  # Should copy selected text to clipboard
  save_to_clipboard: true

