[mouse]
hide_when_typing = true
modifiers = "Command"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
