" vimrc

" Automatically install vim-plug if it is not installed already
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Automatically install missing plugins on startup
autocmd VimEnter *
  \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall --sync | q
  \| endif

" Special case end of file definitions for overriding certain entities
" Added to the of the file because the plugin's will override filetype
" association, which will not happen if we initialize it too soon

" Automatic commands
if has("autocmd")
    " Enable file type detection
    filetype on
    " Treat .json files as .js
    autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript
    " Treat .md files as Markdown
    autocmd BufNewFile,BufRead *.md setlocal filetype=markdown
	" Treat .rs files as Rust files
	autocmd BufNewFile,BufRead *.rs setlocal filetype=rust
endif

augroup configgroup
    autocmd!
    autocmd BufWritePre *.php,*.py,*.js,*.txt,*.hs,*.java,*.md
                \:call <SID>StripTrailingWhitespaces()
augroup END

" Strip trailing whitespace at the end of files. This
" is called on buffer write in the autogroup above.
function! <SID>StripTrailingWhitespaces()
    " save last search & cursor position
    let _s=@/
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    let @/=_s
    call cursor(l, c)
endfunction

""" General Configuration
if filereadable(expand('$VIM_HOME/general.vim'))
  source $VIM_HOME/general.vim
endif
"if filereadable(expand('$VIM_HOME/key-mapping.vim'))
"  source $VIM_HOME/key-mapping.vim
"endif
if filereadable(expand('$VIM_HOME/visual.vim'))
  source $VIM_HOME/visual.vim
endif


""" Plugin Configuration
" All the vim plugins are managed by 'vim-plug'
" List & configuration of plugins separated to several files 'plugins.*.vim'
if filereadable(expand('$VIM_HOME/plugins.vim'))
  source $VIM_HOME/plugins.vim
endif

""" Override Configuration (because of plugins.vim)
"if filereadable(expand('$VIM_HOME/override.vim'))
"  source $VIM_HOME/override.vim
"endif

""" GUI Specific Configuration
"if has('gui_running')
" if filereadable(expand('$VIM_HOME/gui.vim'))
"   source $VIM_HOME/gui.vim
" endif
"endif


""" Theme Configuration
if filereadable(expand('$VIM_HOME/theme.vim'))
  source $VIM_HOME/theme.vim
endif


""" Local Specific Configuration
" Use local vimrc if available
if filereadable(expand('$HOME/.vimrc.local'))
  source $HOME/.vimrc.local
endif
